package com.clinic.api.repository;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;

import com.clinic.api.entity.Appointment;
import com.clinic.api.entity.Appointment.AppointmentStatus;

public interface AppointmentRepository extends JpaRepository<Appointment, Long> {

    /*
     * Get all appointments for a specific patient.
     * Historical records are included.
     */
    List<Appointment> findByPatientIdOrderByAppointmentDateDescAppointmentTimeDesc(
            Long patientId
    );

    /*
     * Get appointments for a patient filtered by status.
     */
    List<Appointment> findByPatientIdAndStatusOrderByAppointmentDateDescAppointmentTimeDesc(
            Long patientId,
            AppointmentStatus status
    );

    /*
     * Get all appointments for one specific date.
     */
    List<Appointment> findByAppointmentDateOrderByAppointmentTimeAsc(
            LocalDate appointmentDate
    );

    /*
     * Get appointments between two dates.
     * Useful for monthly filtering and reports.
     */
    List<Appointment> findByAppointmentDateBetweenOrderByAppointmentDateAscAppointmentTimeAsc(
            LocalDate startDate,
            LocalDate endDate
    );

    /*
     * Get appointments for one date and one status.
     */
    List<Appointment> findByAppointmentDateAndStatusOrderByAppointmentTimeAsc(
            LocalDate appointmentDate,
            AppointmentStatus status
    );

    /*
     * Get appointments assigned to a specific staff member.
     */
    List<Appointment> findByAssignedStaffIdOrderByAppointmentDateDescAppointmentTimeDesc(
            Long assignedStaffId
    );

    /*
     * Get appointments for a specific staff member
     * within a date range.
     */
    List<Appointment> findByAssignedStaffIdAndAppointmentDateBetweenOrderByAppointmentDateAscAppointmentTimeAsc(
            Long assignedStaffId,
            LocalDate startDate,
            LocalDate endDate
    );

    /*
     * Count appointments by status.
     */
    long countByStatus(AppointmentStatus status);

    /*
     * Count appointments for a specific patient.
     */
    long countByPatientId(Long patientId);

    /*
     * Count appointments for a patient by status.
     */
    long countByPatientIdAndStatus(
            Long patientId,
            AppointmentStatus status
    );

    /*
     * Check whether an active appointment already occupies
     * the same patient/date/time/type combination.
     *
     * activeSlotKey is generated by Appointment.java.
     */
    boolean existsByActiveSlotKey(String activeSlotKey);

    /*
     * Used when updating an existing appointment.
     *
     * The current appointment ID is excluded so the appointment
     * does not detect itself as a duplicate.
     */
    boolean existsByActiveSlotKeyAndIdNot(
            String activeSlotKey,
            Long id
    );

    /*
     * Find an appointment using its unique appointment number.
     */
    java.util.Optional<Appointment> findByAppointmentNumber(
            String appointmentNumber
    );

    /*
     * Get active appointments for a specific date.
     */
    List<Appointment> findByAppointmentDateAndStatusInOrderByAppointmentTimeAsc(
            LocalDate appointmentDate,
            List<AppointmentStatus> statuses
    );

    /*
     * Get active appointments for a patient.
     */
    List<Appointment> findByPatientIdAndStatusInOrderByAppointmentDateDescAppointmentTimeDesc(
            Long patientId,
            List<AppointmentStatus> statuses
    );

    /*
     * Check whether a patient has an appointment
     * at an exact date and time among selected statuses.
     *
     * Useful for service-level duplicate validation.
     */
    boolean existsByPatientIdAndAppointmentDateAndAppointmentTimeAndStatusIn(
            Long patientId,
            LocalDate appointmentDate,
            LocalTime appointmentTime,
            List<AppointmentStatus> statuses
    );
}